name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm compile
      - run: pnpm typecheck
      - run: pnpm lint

      - name: test
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' pnpm test

      - name: test-e2e
        run: |
          cd samples/e2e && pnpm i --no-frozen-lockfile
          cd samples/imba && npm i
          xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' pnpm test-e2e --retry 2

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          path: test-results
