name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm compile
      - run: pnpm typecheck
      - run: pnpm lint

      # see: https://github.com/microsoft/vscode-test/blob/main/sample/azure-pipelines.yml
      - name: xvfb
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"

      - run: pnpm test
        env:
          DISPLAY: ':99'

      - run: pnpm test-e2e --retry 2
        env:
          DISPLAY: ':99'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          path: test-results
