name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-14, windows-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm compile
      - run: pnpm typecheck
      - run: pnpm lint

      - name: test
        run: |
          pnpm test

      - name: test-e2e
        run: |
          pnpm -C samples/e2e i
          npm -C samples/imba i
          pnpm test-e2e --retry 2

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          path: test-results
